name: pangeo-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - h5netcdf
  - s3fs
  - prefect
  - pip:
    - git+https://github.com/pangeo-forge/pangeo-forge.git
    - git+https://github.com/pangeo-data/rechunker.git
